import { describe, expect, it } from 'vitest'
import { DEFAULT_CONFIG } from '../../../src/config.js'
import type { NesorConfig } from '../../../src/config.js'
import type { WalkedField, WalkedModel, WalkedSchema } from '../../../src/dmmf/walker.js'
import { type EmittedFile, emitModelFile } from '../../../src/emit/file.js'
import { parseFieldDocs, parseModelDocs } from '../../../src/parse/dsl.js'

function field(
  name: string,
  type: string,
  kind: WalkedField['kind'],
  opts: Partial<Omit<WalkedField, 'name' | 'type' | 'kind' | 'docs'>> & { docs?: string } = {},
): WalkedField {
  const { docs, ...rest } = opts
  return {
    name,
    type,
    kind,
    isList: false,
    isRequired: true,
    isId: false,
    documentation: docs,
    docs: parseFieldDocs(docs, { modelName: 'ModelA', fieldName: name }),
    ...rest,
  }
}

function model(name: string, fields: WalkedField[], modelDocs?: string): WalkedModel {
  return {
    name,
    documentation: modelDocs,
    fields,
    docs: parseModelDocs(modelDocs, { modelName: name }),
  }
}

function schema(models: WalkedModel[], enums: WalkedSchema['enums'] = []): WalkedSchema {
  return { models, enums }
}

function emit(m: WalkedModel, s: WalkedSchema, c: NesorConfig = DEFAULT_CONFIG): EmittedFile {
  const out = emitModelFile(m, s, c)
  if (!out) throw new Error(`expected emission for model ${m.name}, got null`)
  return out
}

describe('emitModelFile', () => {
  it('emits a minimal scalar entity with banner, interface, and meta const', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true }),
      field('name', 'String', 'scalar'),
      field('count', 'Int', 'scalar'),
    ])
    const out = emit(m, schema([m]))
    expect(out.path).toBe('model-a.entity.ts')
    expect(out.text).toContain('AUTO-GENERATED BY NESOR — DO NOT EDIT')
    expect(out.text).toContain('export interface ModelAEntity {')
    expect(out.text).toContain('id: string')
    expect(out.text).toContain('name: string')
    expect(out.text).toContain('count: number')
    expect(out.text).toContain('export const ModelAEntityMeta =')
    expect(out.text).toContain("prismaModel: 'ModelA'")
    expect(out.text).toContain("entityName: 'ModelAEntity'")
    expect(out.text).toContain('excluded: []')
    expect(out.text).toContain('secrets: []')
  })

  it('marks nullable fields with T | null and meta nullable flag', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true }),
      field('opt', 'String', 'scalar', { isRequired: false }),
    ])
    const out = emit(m, schema([m]))
    expect(out.text).toMatch(/opt: string \| null/)
    expect(out.text).toMatch(
      /opt: \{ source: 'opt', kind: 'scalar', tsType: 'string \| null', nullable: true \}/,
    )
  })

  it('renders list fields as T[]', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true }),
      field('tags', 'String', 'scalar', { isList: true }),
    ])
    const out = emit(m, schema([m]))
    expect(out.text).toContain('tags: string[]')
    expect(out.text).toMatch(
      /tags: \{ source: 'tags', kind: 'scalar', tsType: 'string\[\]', list: true \}/,
    )
  })

  it('respects @nesor-rename', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true }),
      field('legacyName', 'String', 'scalar', { docs: '@nesor-rename newName' }),
    ])
    const out = emit(m, schema([m]))
    expect(out.text).toContain('newName: string')
    expect(out.text).not.toContain('legacyName: string')
    expect(out.text).toContain("renamedFrom: 'legacyName'")
  })

  it('honours @nesor-exclude and records it in excluded[]', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true }),
      field('dropped', 'String', 'scalar', { docs: '@nesor-exclude' }),
    ])
    const out = emit(m, schema([m]))
    expect(out.text).not.toContain('dropped: string')
    expect(out.text).toContain("excluded: ['dropped']")
    expect(out.text).toContain('secrets: []')
  })

  it('honours @nesor-secret: excludes the field and records it in both excluded[] and secrets[]', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true }),
      field('password', 'String', 'scalar', { docs: '@nesor-secret' }),
    ])
    const out = emit(m, schema([m]))
    expect(out.text).not.toContain('password: string')
    expect(out.text).toContain("excluded: ['password']")
    expect(out.text).toContain("secrets: ['password']")
  })

  it('returns null for @nesor-skip models', () => {
    const m = model('ModelA', [field('id', 'String', 'scalar', { isId: true })], '@nesor-skip')
    expect(emitModelFile(m, schema([m]), DEFAULT_CONFIG)).toBeNull()
  })

  it('uses @nesor-entity-name override', () => {
    const m = model(
      'ModelA',
      [field('id', 'String', 'scalar', { isId: true })],
      '@nesor-entity-name CustomThing',
    )
    const out = emit(m, schema([m]))
    expect(out.text).toContain('export interface CustomThingEntity {')
    expect(out.text).toContain('export const CustomThingEntityMeta =')
  })

  it('emits inline enum unions by default', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true }),
      field('status', 'Status', 'enum'),
    ])
    const s = schema(
      [m],
      [{ name: 'Status', values: ['Active', 'Archived'], documentation: undefined }],
    )
    const out = emit(m, s)
    expect(out.text).toContain("status: 'Active' | 'Archived'")
  })

  it('emits enum import block when enumStrategy = "import"', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true }),
      field('status', 'Status', 'enum'),
    ])
    const s = schema([m], [{ name: 'Status', values: ['Active'], documentation: undefined }])
    const out = emit(m, s, { ...DEFAULT_CONFIG, enumStrategy: 'import' })
    expect(out.text).toContain("import type { Status } from '@prisma/client'")
    expect(out.text).toContain('status: Status')
  })

  it('emits Decimal advisory comment only when decimalType="string"', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true }),
      field('amount', 'Decimal', 'scalar'),
    ])
    const out = emit(m, schema([m]))
    expect(out.text).toContain('Decimal as string')
    expect(out.text).toContain('amount: string')

    const out2 = emit(m, schema([m]), { ...DEFAULT_CONFIG, decimalType: 'number' })
    expect(out2.text).not.toContain('Decimal as string')
    expect(out2.text).toContain('amount: number')
  })

  it('auto-imports Decimal when decimalType="Decimal" and a Decimal field exists', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true }),
      field('amount', 'Decimal', 'scalar'),
    ])
    const out = emit(m, schema([m]), { ...DEFAULT_CONFIG, decimalType: 'Decimal' })
    expect(out.text).toContain("import type { Decimal } from '@prisma/client/runtime/library'")
    expect(out.text).toMatch(/amount: Decimal\b/)
  })

  it('does not emit the Decimal import when decimalType="Decimal" but no Decimal field exists', () => {
    const m = model('ModelA', [field('id', 'String', 'scalar', { isId: true })])
    const out = emit(m, schema([m]), { ...DEFAULT_CONFIG, decimalType: 'Decimal' })
    expect(out.text).not.toContain('@prisma/client/runtime/library')
  })

  it('refuses to generate when @nesor-brand Decimal collides with decimalType=Decimal', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true, docs: '@nesor-brand Decimal' }),
      field('amount', 'Decimal', 'scalar'),
    ])
    expect(() =>
      emitModelFile(m, schema([m]), { ...DEFAULT_CONFIG, decimalType: 'Decimal' }),
    ).toThrow(/collides with the runtime Decimal type/)
  })

  it('allows @nesor-brand Decimal when decimalType is NOT "Decimal"', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true, docs: '@nesor-brand Decimal' }),
    ])
    const out = emit(m, schema([m]))
    expect(out.text).toContain('export type Decimal = string & {')
  })

  it('produces byte-identical output across runs (idempotency)', () => {
    const m = model('ModelA', [
      field('id', 'String', 'scalar', { isId: true }),
      field('name', 'String', 'scalar'),
    ])
    const a = emit(m, schema([m]))
    const b = emit(m, schema([m]))
    expect(a.text).toBe(b.text)
  })
})
