// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelB               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

import type { ModelAEntity } from './model-a.entity.js'

export interface ModelBEntity {
  id: string
  parentId: string
  parent: ModelAEntity
  label: string
}

export const ModelBEntityMeta = {
  prismaModel: 'ModelB',
  entityName: 'ModelBEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    parentId: { source: 'parentId', kind: 'scalar', tsType: 'string' },
    parent: { source: 'parent', kind: 'relation', tsType: 'ModelAEntity' },
    label: { source: 'label', kind: 'scalar', tsType: 'string' },
  },
  excluded: [],
  secrets: [],
  variants: {},
} as const
