// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelA               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

import type { ModelBEntity } from './model-b.entity.js'

export interface ModelAEntity {
  id: string
  name: string
  tags: ModelBEntity[]
}

export const ModelAEntityMeta = {
  prismaModel: 'ModelA',
  entityName: 'ModelAEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    name: { source: 'name', kind: 'scalar', tsType: 'string' },
    tags: { source: 'tags', kind: 'relation', tsType: 'ModelBEntity[]', list: true },
  },
  excluded: [],
  secrets: [],
  variants: {},
} as const
