// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelB               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

import type { ModelAEntity } from './model-a.entity.js'

export interface ModelBEntity {
  id: string
  label: string
  subjects: ModelAEntity[]
}

export const ModelBEntityMeta = {
  prismaModel: 'ModelB',
  entityName: 'ModelBEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    label: { source: 'label', kind: 'scalar', tsType: 'string' },
    subjects: { source: 'subjects', kind: 'relation', tsType: 'ModelAEntity[]', list: true },
  },
  excluded: [],
  secrets: [],
  variants: {},
} as const
