// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelA               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

export interface ModelAEntity {
  id: string
  visible: string
}

export const ModelAEntityMeta = {
  prismaModel: 'ModelA',
  entityName: 'ModelAEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    visible: { source: 'visible', kind: 'scalar', tsType: 'string' },
  },
  excluded: ['hidden', 'alsoHidden'],
  secrets: ['hidden'],
  variants: {},
} as const
