import type { NesorConfig } from '../config.js'

const WIDTH = 60

function pad(content: string): string {
  const inner = `  ${content}`
  const trimmed = inner.slice(0, WIDTH)
  return `║${trimmed}${' '.repeat(Math.max(0, WIDTH - trimmed.length))}║`
}

/** Build the file-header comment block. `label` appears after `Source: prisma/schema.prisma → `. */
export function makeBanner(label: string, mode: NesorConfig['banner']): string {
  if (mode === 'none') return ''
  if (mode === 'minimal') {
    return `// AUTO-GENERATED BY NESOR — DO NOT EDIT (${label})`
  }
  const top = `╔${'═'.repeat(WIDTH)}╗`
  const bot = `╚${'═'.repeat(WIDTH)}╝`
  return [
    `// ${top}`,
    `// ${pad('AUTO-GENERATED BY NESOR — DO NOT EDIT')}`,
    `// ${pad(`Source: prisma/schema.prisma → ${label}`)}`,
    `// ${pad('Regenerate with: pnpm prisma generate')}`,
    `// ${bot}`,
  ].join('\n')
}
