// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelA               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

export interface ModelAEntity {
  id: string
  requiredText: string
  optionalText: string | null
  requiredList: string[]
  optionalInt: number | null
}

export const ModelAEntityMeta = {
  prismaModel: 'ModelA',
  entityName: 'ModelAEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    requiredText: { source: 'requiredText', kind: 'scalar', tsType: 'string' },
    optionalText: { source: 'optionalText', kind: 'scalar', tsType: 'string | null', nullable: true },
    requiredList: { source: 'requiredList', kind: 'scalar', tsType: 'string[]', list: true },
    optionalInt: { source: 'optionalInt', kind: 'scalar', tsType: 'number | null', nullable: true },
  },
  excluded: [],
  secrets: [],
  variants: {},
} as const
