// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelB               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

export interface ModelBEntity {
  id: string
  label: string
}

export const ModelBEntityMeta = {
  prismaModel: 'ModelB',
  entityName: 'ModelBEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    label: { source: 'label', kind: 'scalar', tsType: 'string' },
  },
  excluded: [],
  secrets: [],
  variants: {},
} as const
