// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelA               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

export interface ModelAEntity {
  id: bigint
  /** Decimal as string. Parse with a Decimal library before doing arithmetic. */
  amount: string
  /** Decimal as string. Parse with a Decimal library before doing arithmetic. */
  discount: string | null
  createdAt: Date
}

export const ModelAEntityMeta = {
  prismaModel: 'ModelA',
  entityName: 'ModelAEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'bigint' },
    amount: { source: 'amount', kind: 'scalar', tsType: 'string' },
    discount: { source: 'discount', kind: 'scalar', tsType: 'string | null', nullable: true },
    createdAt: { source: 'createdAt', kind: 'scalar', tsType: 'Date' },
  },
  excluded: [],
  secrets: [],
  variants: {},
} as const
