// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelA               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

export interface ModelAEntity {
  id: string
  name: string
}

export interface ModelAAuditEntity {
  id: string
  name: string
  deletedAt: Date | null
}

export const ModelAEntityMeta = {
  prismaModel: 'ModelA',
  entityName: 'ModelAEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    name: { source: 'name', kind: 'scalar', tsType: 'string' },
  },
  excluded: ['deletedAt'],
  secrets: [],
  variants: {
    Audit: { include: ['id', 'name', 'deletedAt'] },
  },
} as const
