// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelA               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

export interface ModelAEntity {
  id: string
  name: string
  count: number
}

export const ModelAEntityMeta = {
  prismaModel: 'ModelA',
  entityName: 'ModelAEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    name: { source: 'name', kind: 'scalar', tsType: 'string' },
    count: { source: 'count', kind: 'scalar', tsType: 'number' },
  },
  excluded: [],
  secrets: [],
  variants: {},
} as const
