// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelA               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

import type { ModelBEntity } from './model-b.entity.js'

export interface ModelAEntity {
  id: string
  b: ModelBEntity | null
}

export const ModelAEntityMeta = {
  prismaModel: 'ModelA',
  entityName: 'ModelAEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    b: { source: 'b', kind: 'relation', tsType: 'ModelBEntity | null', nullable: true },
  },
  excluded: [],
  secrets: [],
  variants: {},
} as const
