// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelB               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

import type { ModelAEntity } from './model-a.entity.js'

export interface ModelBEntity {
  id: string
  a: ModelAEntity | null
}

export const ModelBEntityMeta = {
  prismaModel: 'ModelB',
  entityName: 'ModelBEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    a: { source: 'a', kind: 'relation', tsType: 'ModelAEntity | null', nullable: true },
  },
  excluded: [],
  secrets: [],
  variants: {},
} as const
