// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelA               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

export interface ModelAEntity {
  id: string
  name: string
  description: string | null
  count: number
  volatile: string
}

export interface ModelACompactEntity {
  id: string
  name: string
}

export interface ModelASlimEntity {
  id: string
  name: string
  count: number
}

export const ModelAEntityMeta = {
  prismaModel: 'ModelA',
  entityName: 'ModelAEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    name: { source: 'name', kind: 'scalar', tsType: 'string' },
    description: { source: 'description', kind: 'scalar', tsType: 'string | null', nullable: true },
    count: { source: 'count', kind: 'scalar', tsType: 'number' },
    volatile: { source: 'volatile', kind: 'scalar', tsType: 'string' },
  },
  excluded: [],
  secrets: [],
  variants: {
    Compact: { include: ['id', 'name'] },
    Slim: { exclude: ['description'] },
  },
} as const
