// ╔════════════════════════════════════════════════════════════╗
// ║  AUTO-GENERATED BY NESOR — DO NOT EDIT                     ║
// ║  Source: prisma/schema.prisma → model ModelA               ║
// ║  Regenerate with: pnpm prisma generate                     ║
// ╚════════════════════════════════════════════════════════════╝

export interface ModelAEntity {
  id: string
  status: 'Active' | 'Archived' | 'Pending'
  priority: 'Low' | 'Medium' | 'High' | null
}

export const ModelAEntityMeta = {
  prismaModel: 'ModelA',
  entityName: 'ModelAEntity',
  fields: {
    id: { source: 'id', kind: 'scalar', tsType: 'string' },
    status: { source: 'status', kind: 'enum', tsType: "'Active' | 'Archived' | 'Pending'" },
    priority: { source: 'priority', kind: 'enum', tsType: "'Low' | 'Medium' | 'High' | null", nullable: true },
  },
  excluded: [],
  secrets: [],
  variants: {},
} as const
